name: Changed Files
description: Checks changes against target branch

inputs:
  token:
    description: GitHub Token
    required: true

outputs:
  ci:
    description: Should "ci.yml" execute
    value: ${{ steps.changes.outputs.ci }}

runs:
  using: composite
  steps:
    - id: changes
      name: Find changes
      shell: bash
      run: .github/actions/conditional/conditional.sh ${{ github.repository }} ${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
