name: Keycloak CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Maven packages
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/org/keycloak
          key: cache-${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: cache-${{ runner.os }}-m2

      - name: Build Keycloak
        run: |
          mvn clean install -nsu -B -e -DskipTests -Pquarkus,distribution

      - name: Store Keycloak artifacts
        id: store-keycloak
        uses: actions/upload-artifact@v2
        with:
          name: keycloak-artifacts.zip
          retention-days: 2
          path: |
            ~/.m2/repository
            ~/.m2/repository/org/keycloak
            !~/.m2/repository/org/keycloak/**/*.tar.gz

## Tests: Regular distribution

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: cache-${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: cache-${{ runner.os }}-m2
      - name: Download built keycloak
        id: download-keycloak
        uses: actions/download-artifact@v2
        with:
          name: keycloak-artifacts.zip
      - name: Run unit tests
        run: |
          mvn install -nsu -B -DskipTestsuite -DskipExamples -f pom.xml
          TEST_RESULT=$?
          find . -path '*/target/surefire-reports/*.xml' | zip reports-unit-tests.zip -@
          exit $TEST_RESULT

      - name: Unit test reports
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: reports-unit-tests.zip
          retention-days: 14
          path: reports-unit-tests.zip

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/org/keycloak
          key: cache-${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: cache-${{ runner.os }}-m2

      - name: Download built keycloak
        id: download-keycloak
        uses: actions/download-artifact@v2
        with:
          name: keycloak-artifacts.zip

      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run base tests
        run: |
          mvn clean install -nsu -B -Pauth-server-wildfly -DskipTests -f testsuite/pom.xml
          mvn clean install -nsu -B -Pauth-server-wildfly -f testsuite/integration-arquillian/tests/base/pom.xml | misc/log/trimmer.sh
          TEST_RESULT=${PIPESTATUS[0]}
          find . -path '*/target/surefire-reports/*.xml' | zip reports-base-tests.zip -@
          exit $TEST_RESULT

      - name: Base test reports
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: reports-base-tests.zip
          retention-days: 14
          path: reports-base-tests.zip

  test-cluster:
    name: Test Clustering
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check whether this phase should run
        run: echo "GIT_DIFF=$( git diff --name-only HEAD^ | egrep -ic 'crossdc|infinispan' )" >> $GITHUB_ENV

      - name: Cache Maven packages
        if: ${{ github.event_name != 'pull_request' || env.GIT_DIFF != 0 }}
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/org/keycloak
          key: cache-${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: cache-${{ runner.os }}-m2

      - name: Download built keycloak
        if: ${{ github.event_name != 'pull_request' || env.GIT_DIFF != 0 }}
        id: download-keycloak
        uses: actions/download-artifact@v2
        with:
          name: keycloak-artifacts.zip

      - uses: actions/setup-java@v1
        if: ${{ github.event_name != 'pull_request' || env.GIT_DIFF != 0 }}
        with:
          java-version: 1.8

      - name: Run cluster tests
        if: ${{ github.event_name != 'pull_request' || env.GIT_DIFF != 0 }}
        run: |
          mvn clean install -nsu -B -Pauth-server-wildfly,auth-server-cluster,db-mysql,jpa -Dsession.cache.owners=2 -Dbackends.console.output=true -Dauth.server.log.check=false -Dfrontend.console.output=true -Dtest=org.keycloak.testsuite.cluster.**.*Test -f testsuite/integration-arquillian/pom.xml | misc/log/trimmer.sh
          TEST_RESULT=${PIPESTATUS[0]}
          find . -path '*/target/surefire-reports/*.xml' | zip reports-cluster-tests.zip -@
          exit $TEST_RESULT

      - name: Cluster test reports
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: reports-cluster-tests.zip
          retention-days: 14
          path: reports-cluster-tests.zip

  test-crossdc:
    name: Cross-DC Tests
    needs: build
    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: -Xmx1024m
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Check whether this phase should run
        run: echo "GIT_DIFF=$( git diff --name-only HEAD^ | egrep -ic 'crossdc|infinispan' )" >> $GITHUB_ENV

      - uses: actions/setup-java@v1
        if: ${{ github.event_name != 'pull_request' || env.GIT_DIFF != 0 }}
        with:
          java-version: 1.8

      - name: Cache Maven packages
        if: ${{ github.event_name != 'pull_request' || env.GIT_DIFF != 0 }}
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/org/keycloak
          key: cache-${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: cache-${{ runner.os }}-m2

      - name: Download built keycloak
        if: ${{ github.event_name != 'pull_request' || env.GIT_DIFF != 0 }}
        id: download-keycloak
        uses: actions/download-artifact@v2
        with:
          name: keycloak-artifacts.zip

      - name: Run tests
        if: ${{ github.event_name != 'pull_request' || env.GIT_DIFF != 0 }}
        shell: bash
        run: |
          mvn clean install -B -nsu -Pauth-servers-crossdc-jboss,auth-server-wildfly,cache-server-infinispan,app-server-wildfly -DskipTests
          mvn clean install -B -nsu -f testsuite/integration-arquillian/tests/base/pom.xml -Pcache-server-infinispan,auth-servers-crossdc-jboss,auth-server-wildfly "-Dtest=org.keycloak.testsuite.crossdc.**.*,org.keycloak.testsuite.adapter.**.crossdc.**.*" | misc/log/trimmer.sh
          TEST_RESULT=${PIPESTATUS[0]}
          find . -path '*/target/surefire-reports/*.xml' | zip reports-cross-dc-tests.zip -@
          exit $TEST_RESULT

      - name: Cross-DC test reports
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: reports-cross-dc-tests.zip
          retention-days: 14
          path: reports-cross-dc-tests.zip

  test-undertow-map:
    name: Test undertow - map provider
    needs: build
    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: -Xmx2048m
    steps:
      - uses: actions/checkout@v2

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/org/keycloak
          key: cache-${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: cache-${{ runner.os }}-m2

      - name: Download built keycloak
        id: download-keycloak
        uses: actions/download-artifact@v2
        with:
          name: keycloak-artifacts.zip

      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run base tests - undertow
        run: |
          mvn clean install -nsu -B -DskipTests -f testsuite/pom.xml
          mvn clean install -nsu -B -f testsuite/integration-arquillian/tests/base/pom.xml -Dkeycloak.client.provider=map -Dkeycloak.group.provider=map -Dkeycloak.role.provider=map | misc/log/trimmer.sh
          TEST_RESULT=${PIPESTATUS[0]}
          find . -path '*/target/surefire-reports/*.xml' | zip reports-base-undertow-tests.zip -@
          exit $TEST_RESULT

      - name: Base test - undertow reports
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: reports-base-undertow-tests.zip
          retention-days: 14
          path: reports-base-undertow-tests.zip

### Tests: Quarkus distribution

  quarkus-test:
    name: Quarkus Test
    needs: build
    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: -Xmx2048m
    steps:
      - uses: actions/checkout@v2

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/org/keycloak
          key: cache-${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: cache-${{ runner.os }}-m2

      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run Quarkus unit tests
        run: |
          mvn install -nsu -B -Pquarkus -f quarkus/pom.xml
          mvn clean install -nsu -B -Pquarkus,auth-server-quarkus -DskipTests -f testsuite/pom.xml
          mvn clean install -nsu -B -Pquarkus,auth-server-quarkus -f testsuite/integration-arquillian/tests/base/pom.xml -Dtest='!org.keycloak.testsuite.adapter.**,!**.crossdc.**,!**.cluster.**' | misc/log/trimmer.sh
          TEST_RESULT=${PIPESTATUS[0]}
          find . -path '*/target/surefire-reports/*.xml' | zip reports-base-unit-tests.zip -@
          exit $TEST_RESULT

      - name: Base / unit test reports
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: reports-base-unit-tests.zip
          retention-days: 14
          path: reports-base-unit-tests.zip

  quarkus-test-adapter:
    name: Quarkus Test Adapter
    needs: build
    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: -Xmx1024m
    steps:
      - uses: actions/checkout@v2
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/org/keycloak
          key: cache-${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: cache-${{ runner.os }}-m2
      - name: Download built keycloak
        id: download-keycloak
        uses: actions/download-artifact@v2
        with:
          name: keycloak-artifacts.zip
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run adapter tests
        run: |
          mvn clean install -nsu -B -Pquarkus,auth-server-quarkus -DskipTests -f testsuite/pom.xml
          mvn clean install -nsu -B -Pquarkus,auth-server-quarkus -f testsuite/integration-arquillian/tests/base/pom.xml -Dtest=org.keycloak.testsuite.adapter.** | misc/log/trimmer.sh
          TEST_RESULT=${PIPESTATUS[0]}
          find . -path '*/target/surefire-reports/*.xml' | zip reports-adapter-tests.zip -@
          exit $TEST_RESULT

      - name: Adapter test reports
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: reports-adapter-tests.zip
          retention-days: 14
          path: reports-adapter-tests.zip

  quarkus-test-cluster:
    name: Quarkus Test Clustering
    needs: build
    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: -Xmx2048m
    steps:
      - uses: actions/checkout@v2
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/org/keycloak
          key: cache-${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: cache-${{ runner.os }}-m2
      - name: Download built keycloak
        id: download-keycloak
        uses: actions/download-artifact@v2
        with:
          name: keycloak-artifacts.zip
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run cluster tests
        run: |
          mvn clean install -nsu -B -Pquarkus,auth-server-quarkus -DskipTests -f testsuite/pom.xml
          mvn clean install -nsu -B -Pauth-server-cluster-quarkus -Dsession.cache.owners=2 -Dtest=**.cluster.** -f testsuite/integration-arquillian/pom.xml  | misc/log/trimmer.sh
          TEST_RESULT=${PIPESTATUS[0]}
          find . -path '*/target/surefire-reports/*.xml' | zip reports-cluster-tests.zip -@
          exit $TEST_RESULT

      - name: Cluster test reports
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: reports-cluster-tests.zip
          retention-days: 14
          path: reports-cluster-tests.zip
